AirbnbProj:
  outputs:
    dev:
      account: PSMZQQL-TJ45721
      database: AIRBNB
      password: Training123456
      role: ACCOUNTADMIN
      schema: DBT_AIRBNB
      threads: 1
      type: snowflake
      user: feblearning
      warehouse: MY_LARGEWH
  target: dev
AirbnbProject:
  outputs:
    dev:
      account: QHBNPTY-HW85053
      database: AIRBNB_DEMO
      password: Training123456
      role: ACCOUNTADMIN
      schema: dbtairbnb_tgt
      threads: 1
      type: snowflake
      user: march2026learning
      warehouse: LARGE_WH
  target: dev
Airbnb_bq_proj:
  outputs:
    dev:
      dataset: dbt_airbnb
      job_execution_timeout_seconds: 300
      job_retries: 1
      keyfile: C:\Users\msk\Airbnb_bq\mysampleproject-491106-79b1b7c757d1.json
      location: US
      method: service-account
      priority: interactive
      project: mysampleproject-491106
      threads: 1
      type: bigquery
  target: dev
